name: Selenium Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest # Using linux machine

    steps:
    - uses: actions/checkout@v2 # Checkout the code
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1 # Setup JAVA
      with:
        java-version: 1.8
         
    
    - name: Setup Chrome 
    - run: chrome --version
    - uses: browser-actions/setup-chrome@latest
      with:
          chrome-version: beta
      
        
    - name: Build with Maven
      run: mvn clean test
